//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28.04.2019 02:22:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Klassenplaner.Data.Models
{
    public partial class Lesson {

        public Lesson()
        {
            OnCreated();
        }

        public virtual System.Guid Id
        {
            get;
            set;
        }

        public virtual System.DateTime? DateCreated
        {
            get;
            set;
        }

        public virtual System.DateTime? DateUpdated
        {
            get;
            set;
        }

        public virtual short WeekDay
        {
            get;
            set;
        }

        public virtual System.Guid ClassId
        {
            get;
            set;
        }

        public virtual System.Guid TeacherId
        {
            get;
            set;
        }

        public virtual Class Class
        {
            get;
            set;
        }

        public virtual Teacher Teacher
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
