//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28.04.2019 02:22:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Klassenplaner.Data.Models
{
    public partial class School {

        public School()
        {
            this.Teachers = new List<Teacher>();
            this.Classes = new List<Class>();
            OnCreated();
        }

        public virtual System.Guid Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string State
        {
            get;
            set;
        }

        public virtual string City
        {
            get;
            set;
        }

        public virtual eCountry Country
        {
            get;
            set;
        }

        public virtual IList<Teacher> Teachers
        {
            get;
            set;
        }

        public virtual IList<Class> Classes
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
